### ISSUE TITLE
Postgres authentication issue

### ISSUE THREAD

**Issue by ansermino** [ShyftNetwork/shyft_go-ethereum#109]
#### System information
(Development branch)
```
Geth
Version: 1.8.3-unstable
Git Commit: fca85ebb8ac1a3f49e28f92535ff9c64d6ea0cf1
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

#### Expected behaviour
Geth should succesfully start.

#### Actual behaviour
Errors on postgres authentication:
```
david:~/go/src/github.com/ShyftNetwork/go-empyrean$ sudo ./shyft-geth.sh --start

INFO [10-03|14:37:42] Maximum peer count                       ETH=25 LES=0 total=25
INFO [10-03|14:37:42] Starting peer-to-peer node               instance=Geth/ShyftTestnetNode/v1.8.3-unstable-fca85ebb/linux-amd64/go1.10
INFO [10-03|14:37:42] Allocated cache and file handles         database=/home/david/go/src/github.com/ShyftNetwork/go-empyrean/shyftData/geth/chaindata cache=768 handles=512
INFO [10-03|14:37:42] Writing default main-net genesis block 
INFO [10-03|14:37:42] Persisted trie from memory database      nodes=12356 size=2.34mB time=37.196594ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
ERROR OPENING DB, NOT INITIALIZING
panic: pq: password authentication failed for user "postgres"

goroutine 1 [running]:
github.com/ShyftNetwork/go-empyrean/core.Connect(0xf9d178, 0x2c, 0x50)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/core/db.go:52 +0x11c
github.com/ShyftNetwork/go-empyrean/core.DbExists(0xf7470e, 0x7, 0xf72f92, 0x6, 0x1bb81e0)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/core/db.go:114 +0x39
github.com/ShyftNetwork/go-empyrean/core.InitDB(0x1, 0xdc09e0, 0xc42026c101)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/core/db.go:31 +0x81
github.com/ShyftNetwork/go-empyrean/core.DBConnection(0xdc09e0, 0xc430fb9c2c, 0xc42050a2c8)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/core/db.go:134 +0x62
github.com/ShyftNetwork/go-empyrean/core.BlockExists(0xc42026c1e0, 0x42, 0xe6346a90d018a145)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/core/shyft_database_util.go:209 +0x4e
github.com/ShyftNetwork/go-empyrean/core.SetupGenesisBlock(0x11095c0, 0xc42039c090, 0xc4202df080, 0xc42039c090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/core/genesis.go:266 +0x24e
github.com/ShyftNetwork/go-empyrean/eth.New(0xc42000c720, 0xc420511800, 0xf22f60, 0xc42050f838, 0x426568)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/eth/backend.go:148 +0x133
github.com/ShyftNetwork/go-empyrean/cmd/utils.RegisterEthService.func2(0xc42000c720, 0xc420520270, 0xc42050fb28, 0xc42000c6e0, 0x2)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/cmd/utils/flags.go:1136 +0x3d
github.com/ShyftNetwork/go-empyrean/node.(*Node).Start(0xc420385b80, 0x0, 0x0)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/node/node.go:182 +0x42c
github.com/ShyftNetwork/go-empyrean/cmd/utils.StartNode(0xc420385b80)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/cmd/utils/cmd.go:63 +0x2f
main.startNode(0xc4202a4840, 0xc420385b80)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/cmd/geth/main.go:230 +0x43
main.geth(0xc4202a4840, 0x10039f8, 0xb2d05e00)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/cmd/geth/main.go:220 +0x43
github.com/ShyftNetwork/go-empyrean/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xde7900, 0x1004f38, 0xc4202a4840, 0xc4202a4840, 0xc42050ff48)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/ShyftNetwork/go-empyrean/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42023a340, 0xc4200ca000, 0x11, 0x12, 0x0, 0x0)
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x5ee
main.main()
	/home/david/go/src/github.com/ShyftNetwork/go-empyrean/build/_workspace/src/github.com/ShyftNetwork/go-empyrean/cmd/geth/main.go:209 +0x55
```

#### Steps to reproduce the behaviour
1. Clone repo
2. Start postgres
3. `./shyft-geth --setup`
4. `./shyft-geth --start`

***(NOTE: Running `./shyft-geth.sh --start` a second time Geth starts successfully)***

**Comment by ansermino** [comment]
This is also causing issues for the `./shyft-geth.sh --setup` command.

**Comment by ansermino** [comment]
Tried to reproduce in a fresh Ubuntu 18.04 VM.

```
sudo apt install postgresql
sudo -u postgres createuser david
```

When running from a fresh clone I get:
```
david:~/go/src/github.com/ShyftNetwork/go-empyrean$ ./shyft-geth.sh --setup
Creating postgres db...
psql: FATAL:  Peer authentication failed for user "postgres"
```

**Comment by dbkbali** [comment]
@ansermino closing see  #106 - when you createuser david (assuming this is your development user) you need to provide super user privileges (--superuser flag) - see postgresql docs here  https://www.postgresql.org/docs/10/static/app-createuser.html. Also for a local development install the  implicit assumption is that no password is required for access to the postgres instance by the postgresql user or the development user. If this is not the case appropriate mods should be made to core/db.go - with respect to the variable connStrDefault.
